apiVersion: v1
kind: Pod
metadata:
  name: python3-pod
  labels:
    app: python3
spec:
  containers:
  - name: python3-container
    image: python:3.6
    command: ['python3', '-c', 'print("Hello, World!")']
  restartPolicy: Never